aea_version: 0.1.10
agent_name: carpark_aea
authors: ''
connections:
- oef
default_connection: oef
description: ''
ledger_apis:
- ledger_api:
    addr: alpha.fetch-ai.com
    ledger: fetchai
    port: 80
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
- private_key_path:
    ledger: default
    path: default_private_key.pem
- private_key_path:
    ledger: fetchai
    path: fet_private_key.txt
- private_key_path:
    ledger: ethereum
    path: eth_private_key.txt
protocols:
- default
- fipa
- oef
registry_path: ../packages
skills:
- carpark_detection
- error
url: ''
version: v1
